export const TYPES = {
    ProviderRepository: Symbol.for("ProviderRepository"),
    CreateProviderUseCase: Symbol.for("CreateProviderUseCase"),
    GetProviderUseCase: Symbol.for("GetProviderUseCase"),
    ListProvidersUseCase: Symbol.for("ListProvidersUseCase"),
    UpdateProviderUseCase: Symbol.for("UpdateProviderUseCase"),
    DeleteProviderUseCase: Symbol.for("DeleteProviderUseCase"),
    ProviderController: Symbol.for("ProviderController"),
    ProviderFinder: Symbol.for("ProviderFinder"),
    AddProviderModelUseCase: Symbol.for("AddProviderModelUseCase"),
    RemoveProviderModelUseCase: Symbol.for("RemoveProviderModelUseCase"),
    ActivateProviderModelUseCase: Symbol.for("ActivateProviderModelUseCase"),
    DeactivateProviderModelUseCase: Symbol.for("DeactivateProviderModelUseCase"),
    ProviderModelController: Symbol.for("ProviderModelController"),
};
